config/routes.rb
Rails.application.routes.draw do
  resources :birds

end

app/models/bird.rb
class Bird
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  
  field :name, type: String
  field :family, type: String
  field :added, type: String
  field :visible, type: Mongoid::Boolean

  embeds_many :continents
  accepts_nested_attributes_for :continents

  validate :validate_continents_count

  def as_json(*args)
    res = super
    res["id"] = res.delete("_id").to_s
    res
  end

  def validate_continents_count
    if self.continents.size < 1
      errors.add(:continents, "Need 1 or more items")
    end
  end

end

app/models/continent.rb
class Continent
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  
  field :name, type: String
  embedded_in :bird
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  
  def json_request?
    request.format.json?
  end
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  skip_before_filter :verify_authenticity_token, if: :json_request?
  before_action :set_bird, only: [:show, :edit, :update, :destroy]

  # GET /birds format html or json
  def index
    @birds = Bird.where({visible: true})
  end

  # GET /birds/1.<html|json> format html or json
  def show
    respond_to do |format|
      if @bird.blank?
        format.html { render :new, error: 'Bird with given id not found.', status: :not_found }
        format.json { head :not_found }
      else
        format.html { render :show, status: :ok }
        format.json { render :show, status: :ok}
      end
    end
  end

  # GET /birds/new format html 
  def new
    @bird = Bird.new
  end

  # POST /birds.<html|json> format html or json
  def create
    @bird = Bird.new(bird_params)
    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: 'Bird was successfully created.' }
        format.json { render :show, status: :created, location: @bird }
      else
        format.html { render :new }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1.<html|json> format html or json
  def destroy
    @bird.destroy if @bird.present?
    respond_to do |format|
      if @bird.blank?
        format.html { render :new, error: 'Bird with given id not found.', status: :not_found }
        format.json { head :not_found }
      else
        format.html { redirect_to birds_url, notice: 'Bird was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # callbacks to share common constraints between actions.
    def set_bird
      begin
        @bird = Bird.find(params[:id])
      rescue
        logger.debug(" Bird with id #{params[:id]} not found}")
        @bird = nil
      end
      @bird
    end

    # For allowing only the white list through. 
    def bird_params
      params.require(:bird).permit(:name, :family, :added, :visible, continents_attributes: [:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/birds/_form.html.erb
<%= form_for(@bird) do |f| %>
  <% if @bird.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
      <% @bird.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :added %><br>
    <%= f.text_field :added %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birds/edit.html.erb
<h1>Editing Bird</h1>

<%= render 'form' %>

<%= link_to 'Show', @bird %> |
<%= link_to 'Back', birds_path %>

app/views/birds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Birds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Continents</th>
      <th>Added</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @birds.each do |bird| %>
      <tr>
        <td><%= bird.name %></td>
        <td><%= bird.family %></td>
        <td><%= bird.continents %></td>
        <td><%= bird.added %></td>
        <td><%= bird.visible %></td>
        <td><%= link_to 'Show', bird %></td>
        <td><%= link_to 'Destroy', bird, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bird', new_bird_path %>

app/views/birds/new.html.erb
<h1>New Bird</h1>

<%= render 'form' %>

<%= link_to 'Back', birds_path %>

app/views/birds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bird.name %>
</p>

<p>
  <strong>Family:</strong>
  <%= @bird.family %>
</p>

<p>
  <strong>Continents:</strong>
  <%= @bird.continents %>
</p>

<p>
  <strong>Added:</strong>
  <%= @bird.added %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @bird.visible %>
</p>

<%= link_to 'Back', birds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BirdsApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>